name: Daily Telegram Repo Summary

on:
  schedule:
    - cron: '35 8 * * *'  # Runs every day at 2:05 PM IST (08:35 UTC)

jobs:
  send-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get repo stats and send to Telegram
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REPO: araafroyall/Cleaner-Royall
        run: |
          escape_md2() {
            echo "$1" | sed \
              -e 's/\\/\\\\/g' \
              -e 's/_/\\_/g' \
              -e 's/\*/\\*/g' \
              -e 's/\[/\\[/g' \
              -e 's/\]/\\]/g' \
              -e 's/(/\\(/g' \
              -e 's/)/\\)/g' \
              -e 's/~/\\~/g' \
              -e 's/`/\\`/g' \
              -e 's/>/\\>/g' \
              -e 's/#/\\#/g' \
              -e 's/\+/\\+/g' \
              -e 's/-/\\-/g' \
              -e 's/=/\\=/g' \
              -e 's/|/\\|/g' \
              -e 's/{/\\{/g' \
              -e 's/}/\\}/g' \
              -e 's/\./\\./g' \
              -e 's/!/\\!/g'
          }

          # Fetch repository info
          REPO_DATA=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$REPO)
          OPEN_ISSUES=$(echo "$REPO_DATA" | jq '.open_issues_count')
          STARS=$(echo "$REPO_DATA" | jq '.stargazers_count')
          SIZE=$(echo "$REPO_DATA" | jq '.size')
          LANGUAGE=$(echo "$REPO_DATA" | jq -r '.language')
          REPO_URL=$(echo "$REPO_DATA" | jq -r '.html_url')

          # Fetch closed issues count
          CLOSED_ISSUES=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=repo:$REPO+is:issue+is:closed" | jq '.total_count')

          # MarkdownV2 escapes
          ESCAPED_HEADER=$(escape_md2 "Cleaner-Royall GitHub Repo Summary")
          ESCAPED_REPO=$(escape_md2 "$REPO")
          ESCAPED_REPO_URL=$(escape_md2 "$REPO_URL")
          ESCAPED_STARS=$(escape_md2 "$STARS")
          ESCAPED_SIZE=$(escape_md2 "$SIZE")
          ESCAPED_LANGUAGE=$(escape_md2 "$LANGUAGE")
          ESCAPED_OPEN_ISSUES=$(escape_md2 "$OPEN_ISSUES")
          ESCAPED_CLOSED_ISSUES=$(escape_md2 "$CLOSED_ISSUES")

          # Build the message line by line, escaping every dash!
          MSG="*${ESCAPED_HEADER}*"$'\n'
          MSG+="\- Repo: [${ESCAPED_REPO}](${REPO_URL})"$'\n'
          MSG+="\- Stars: ${ESCAPED_STARS}"$'\n'
          MSG+="\- Codespace size: ${ESCAPED_SIZE} KB"$'\n'
          MSG+="\- Language: ${ESCAPED_LANGUAGE}"$'\n'
          MSG+="\- Open issues: ${ESCAPED_OPEN_ISSUES}"$'\n'
          MSG+="\- Closed issues: ${ESCAPED_CLOSED_ISSUES}"

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            --data-urlencode text="$MSG" \
            -d parse_mode=MarkdownV2 \
            -d disable_web_page_preview=true