name: Daily Telegram Repo Summary

on:
  schedule:
    - cron: '35 8 * * *'  # Runs every day at 2:05 PM IST (08:35 UTC)

jobs:
  send-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get repo stats and send to Telegram
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REPO: araafroyall/Cleaner-Royall
        run: |
          escape_md2() {
            echo "$1" | sed \
              -e 's/\\/\\\\/g' \
              -e 's/_/\\_/g' \
              -e 's/\*/\\*/g' \
              -e 's/\[/\\[/g' \
              -e 's/\]/\\]/g' \
              -e 's/(/\\(/g' \
              -e 's/)/\\)/g' \
              -e 's/~/\\~/g' \
              -e 's/`/\\`/g' \
              -e 's/>/\\>/g' \
              -e 's/#/\\#/g' \
              -e 's/\+/\\+/g' \
              -e 's/-/\\-/g' \
              -e 's/=/\\=/g' \
              -e 's/|/\\|/g' \
              -e 's/{/\\{/g' \
              -e 's/}/\\}/g' \
              -e 's/\./\\./g' \
              -e 's/!/\\!/g'
          }

          # Fetch repository info
          REPO_DATA=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO)

          OPEN_ISSUES=$(echo "$REPO_DATA" | jq '.open_issues_count')
          STARS=$(echo "$REPO_DATA" | jq '.stargazers_count')
          SIZE=$(echo "$REPO_DATA" | jq '.size')
          LANGUAGE=$(echo "$REPO_DATA" | jq -r '.language')
          REPO_URL=$(echo "$REPO_DATA" | jq -r '.html_url')

          # Fetch closed issues count
          CLOSED_ISSUES=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=repo:$REPO+is:issue+is:closed" | jq '.total_count')

          # Safely escape all dynamic values for MarkdownV2
          ESCAPED_HEADER=$(escape_md2 "Cleaner-Royall GitHub Repo Summary")
          ESCAPED_REPO=$(escape_md2 "$REPO")
          ESCAPED_REPO_URL=$(escape_md2 "$REPO_URL")
          ESCAPED_STARS=$(escape_md2 "$STARS")
          ESCAPED_SIZE=$(escape_md2 "$SIZE")
          ESCAPED_LANGUAGE=$(escape_md2 "$LANGUAGE")
          ESCAPED_OPEN_ISSUES=$(escape_md2 "$OPEN_ISSUES")
          ESCAPED_CLOSED_ISSUES=$(escape_md2 "$CLOSED_ISSUES")

          # Format the message with proper MarkdownV2 escaping and newlines
          MSG="*${ESCAPED_HEADER}*"$'\n'
          MSG+=$(escape_md2 "- Repo: ")"["${ESCAPED_REPO}"](${REPO_URL})"$'\n'
          MSG+=$(escape_md2 "- Stars: ${STARS}")$'\n'
          MSG+=$(escape_md2 "- Codespace size: ${SIZE} KB")$'\n'
          MSG+=$(escape_md2 "- Language: ${LANGUAGE}")$'\n'
          MSG+=$(escape_md2 "- Open issues: ${OPEN_ISSUES}")$'\n'
          MSG+=$(escape_md2 "- Closed issues: ${CLOSED_ISSUES}")

          # Send to Telegram
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            --data-urlencode text="$MSG" \
            -d parse_mode=MarkdownV2 \
            -d disable_web_page_preview=true