name: Daily Telegram Repo Summary

on:
  schedule:
    - cron: '20 8 * * *'  # Runs every day at 1:46 PM IST
jobs:
  send-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get repo stats and send to Telegram
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Built-in token, no need to create
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REPO: araafroyall/Cleaner-Royall
        run: |
          escape_md2() {
            echo "$1" | sed \
              -e 's/\\/\\\\/g' \
              -e 's/_/\\_/g' \
              -e 's/\*/\\*/g' \
              -e 's/\[/\\[/g' \
              -e 's/\]/\\]/g' \
              -e 's/(/\\(/g' \
              -e 's/)/\\)/g' \
              -e 's/~/\\~/g' \
              -e 's/`/\\`/g' \
              -e 's/>/\\>/g' \
              -e 's/#/\\#/g' \
              -e 's/\+/\\+/g' \
              -e 's/-/\\-/g' \
              -e 's/=/\\=/g' \
              -e 's/|/\\|/g' \
              -e 's/{/\\{/g' \
              -e 's/}/\\}/g' \
              -e 's/\./\\./g' \
              -e 's/!/\\!/g'
          }

          # Fetch repository info
          REPO_DATA=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO)

          OPEN_ISSUES=$(echo "$REPO_DATA" | jq '.open_issues_count')
          STARS=$(echo "$REPO_DATA" | jq '.stargazers_count')
          SIZE=$(echo "$REPO_DATA" | jq '.size')
          LANGUAGE=$(echo "$REPO_DATA" | jq -r '.language')
          REPO_URL=$(echo "$REPO_DATA" | jq -r '.html_url')

          # Fetch closed issues count
          CLOSED_ISSUES=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=repo:$REPO+is:issue+is:closed" | jq '.total_count')

          # Safely escape all dynamic values for MarkdownV2
          ESCAPED_REPO=$(escape_md2 "$REPO")
          ESCAPED_REPO_URL=$(escape_md2 "$REPO_URL")
          ESCAPED_LANGUAGE=$(escape_md2 "$LANGUAGE")
          
          # Format the message with proper MarkdownV2 escaping
          MSG=$'*Cleaner\\-Royall GitHub Repo Summary*\n'\
'- Repo: ['"${ESCAPED_REPO}"']('"${ESCAPED_REPO_URL}"')\n'\
'- Stars: '"${STARS}"'\n'\
'- Codespace size: '"${SIZE}"' KB\n'\
'- Language: '"${ESCAPED_LANGUAGE}"'\n'\
'- Open issues: '"${OPEN_ISSUES}"'\n'\
'- Closed issues: '"${CLOSED_ISSUES}"

          # Send to Telegram
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            --data-urlencode text="$MSG" \
            -d parse_mode=MarkdownV2 \
            -d disable_web_page_preview=true