name: GitHub to Telegram Notifications

on:
  push:
  pull_request:
  issues:
  issue_comment:
  release:
  create:
  delete:
  discussion_comment:
  workflow_dispatch:
  repository_dispatch:
  fork:
  watch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Telegram Notification
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        EVENT_NAME="${{ github.event_name }}"
        ACTOR="${{ github.actor }}"
        REPO="${{ github.repository }}"
        ACTION="${{ github.event.action }}"
        URL=""

        if [ "$EVENT_NAME" = "push" ]; then
          URL="${{ github.event.head_commit.url }}"
        elif [ "$EVENT_NAME" = "pull_request" ]; then
          URL="${{ github.event.pull_request.html_url }}"
        elif [ "$EVENT_NAME" = "issues" ]; then
          URL="${{ github.event.issue.html_url }}"
        elif [ "$EVENT_NAME" = "issue_comment" ]; then
          URL="${{ github.event.comment.html_url }}"
        elif [ "$EVENT_NAME" = "release" ]; then
          URL="${{ github.event.release.html_url }}"
        elif [ "$EVENT_NAME" = "discussion_comment" ]; then
          URL="${{ github.event.discussion.html_url }}"
        fi

        if [ -z "$URL" ]; then
          URL="https://github.com/${REPO}"
        fi

        MSG="🚀 *GitHub Action Report*

*Event:* ${EVENT_NAME}
*Action:* ${ACTION}
*Repo:* ${REPO}
*By:* ${ACTOR}

[🔗 View on GitHub](${URL})"

        RESPONSE=$(curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
          -d chat_id="$TELEGRAM_CHAT_ID" \
          -d text="$MSG" \
          -d parse_mode=Markdown)

        OK=$(echo "$RESPONSE" | grep -o '"ok":true')
        if [ -z "$OK" ]; then
          echo "❌ Telegram API call failed!"
          echo "$RESPONSE"
          exit 1
        fi
