name: GitHub to Telegram Notifications

on:
  push:
  pull_request:
  issues:
  issue_comment:
  release:
  create:
  delete:
  discussion_comment:
  workflow_dispatch:
  repository_dispatch:
  fork:
  watch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Telegram Notification
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        EVENT_NAME="${{ github.event_name }}"
        ACTOR="${{ github.actor }}"
        REPO="${{ github.repository }}"
        ACTION="${{ github.event.action }}"
        URL="https://github.com/${REPO}"
        MSG="🚀 *GitHub Event Triggered*\n\n*Event:* ${EVENT_NAME}\n*Action:* ${ACTION}\n*Repo:* ${REPO}\n*By:* ${ACTOR}\n\n[🔗 Open Repo](${URL})"

        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
        -d chat_id="$TELEGRAM_CHAT_ID" \
        -d text="$MSG" \
        -d parse_mode=Markdown
