name: GitHub to Telegram Notifications

on:
  push:
  pull_request:
  issues:
  issue_comment:
  release:
  create:
  delete:
  discussion_comment:
  workflow_dispatch:
  repository_dispatch:
  fork:
  watch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Telegram Notification
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        EVENT_NAME=$(echo "$GITHUB_CONTEXT" | jq -r '.event_name')
        ACTION=$(echo "$GITHUB_CONTEXT" | jq -r '.event.action // empty')
        ACTOR=$(echo "$GITHUB_CONTEXT" | jq -r '.actor')
        REPO=$(echo "$GITHUB_CONTEXT" | jq -r '.repository.full_name')

        URL=""
        case "$EVENT_NAME" in
          push)
            URL=$(echo "$GITHUB_CONTEXT" | jq -r '.event.head_commit.url // empty')
            ;;
          pull_request)
            URL=$(echo "$GITHUB_CONTEXT" | jq -r '.event.pull_request.html_url // empty')
            ;;
          issues)
            URL=$(echo "$GITHUB_CONTEXT" | jq -r '.event.issue.html_url // empty')
            ;;
          issue_comment)
            URL=$(echo "$GITHUB_CONTEXT" | jq -r '.event.comment.html_url // empty')
            ;;
          release)
            URL=$(echo "$GITHUB_CONTEXT" | jq -r '.event.release.html_url // empty')
            ;;
          discussion_comment)
            URL=$(echo "$GITHUB_CONTEXT" | jq -r '.event.discussion.html_url // empty')
            ;;
        esac

        if [ -z "$URL" ]; then
          URL="https://github.com/$REPO"
        fi

        MSG="🚀 *GitHub Action Report*

*Event:* $EVENT_NAME
*Action:* $ACTION
*Repo:* $REPO
*By:* $ACTOR

[🔗 View on GitHub]($URL)"

        RESPONSE=$(curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
          -d chat_id="$TELEGRAM_CHAT_ID" \
          -d text="$MSG" \
          -d parse_mode=Markdown)

        OK=$(echo "$RESPONSE" | grep -o '"ok":true')
        if [ -z "$OK" ]; then
          echo "❌ Telegram API call failed!"
          echo "$RESPONSE"
          exit 1
        fi
