name: 📬 Notify via ntfy.sh

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📤 Clean send to ntfy.sh
        env:
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS_JSON: ${{ toJson(github.event.issue.labels) }}
        run: |
          LABELS=$(echo "$LABELS_JSON" | jq -r '.[].name' | paste -sd ',' - 2>/dev/null || echo "None")
          
          printf "🆕 New Issue #%s\n🔖 %s\n🏷️ %s\n📝 %s" \
            "${NUMBER:-Manual Trigger}" \
            "${TITLE:-(no title)}" \
            "$LABELS" \
            "${BODY:-(no body)}" \
          | iconv -c -t utf-8 \
          | curl -H "Content-Type: text/plain" \
                 --data-binary @- \
                 "https://ntfy.sh/${{ secrets.FEEDBACK_KEY }}"