name: 📬 Send Issue Feedback to ntfy

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📤 Send to ntfy.sh
        env:
          NTFY_KEY: ${{ secrets.FEEDBACK_KEY }}
        run: |
          TITLE="${{ github.event.issue.title }}"
          BODY="${{ github.event.issue.body }}"
          LABELS="$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name' | paste -sd ',')"

          TEXT="🆕 New Issue Created\n🔖 Title: $TITLE\n🏷️ Labels: $LABELS\n📝 $BODY"

          curl -u "feedback:$NTFY_KEY" \
            -d "$TEXT" \
            https://ntfy.sh/sampleRoyall
