name: 📬 Notify via ntfy.sh

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📤 Clean send to ntfy.sh
        run: |
          LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name' | paste -sd ',' -)

          printf "🆕 New Issue\n🔖 %s\n🏷️ %s\n📝 %s" \
            "${{ github.event.issue.title }}" \
            "$LABELS" \
            "${{ github.event.issue.body }}" \
          | iconv -c -t utf-8 \
          | curl -H "Content-Type: text/plain" \
                 --data-binary @- \
                 "https://ntfy.sh/${{ secrets.FEEDBACK_KEY }}"