name: 📬 Notify Issue via ntfy.sh

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📤 Send to ntfy.sh
        run: |
          TITLE="${{ github.event.issue.title }}"
          BODY="${{ github.event.issue.body }}"
          LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name' | paste -sd ',' -)

          TEXT=$(printf "🆕 New Issue\n🔖 %s\n🏷️ %s\n📝 %s" "$TITLE" "$LABELS" "$BODY")

          curl -d "$TEXT" \
            "https://ntfy.sh/${{ secrets.FEEDBACK_KEY }}"
