name: 📬 Notify Issue via ntfy.sh

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📤 Send to ntfy.sh
        run: |
          echo "🔧 Preparing ntfy message..."

          TITLE=$(echo "${{ github.event.issue.title }}" | sed 's/"/\\"/g')
          BODY=$(echo "${{ github.event.issue.body }}" | sed 's/"/\\"/g')
          LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name' | paste -sd ',' -)

          MESSAGE="🆕 New Issue\n🔖 $TITLE\n🏷️ $LABELS\n📝 $BODY"

          curl -H "Content-Type: text/plain" \
               -d "$MESSAGE" \
               "https://ntfy.sh/${{ secrets.FEEDBACK_KEY }}"
